// automatically generated by the FlatBuffers compiler, do not modify

// @generated

use core::cmp::Ordering;
use core::mem;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod bridge {

    use core::cmp::Ordering;
    use core::mem;

    extern crate flatbuffers;
    use self::flatbuffers::{EndianScalar, Follow};
    #[allow(unused_imports, dead_code)]
    pub mod schema {

        use core::cmp::Ordering;
        use core::mem;

        extern crate flatbuffers;
        use self::flatbuffers::{EndianScalar, Follow};

        pub enum BoundingBoxOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct BoundingBox<'a> {
            pub _tab: flatbuffers::Table<'a>,
        }

        impl<'a> flatbuffers::Follow<'a> for BoundingBox<'a> {
            type Inner = BoundingBox<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: flatbuffers::Table::new(buf, loc),
                }
            }
        }

        impl<'a> BoundingBox<'a> {
            pub const VT_X1: flatbuffers::VOffsetT = 4;
            pub const VT_Y1: flatbuffers::VOffsetT = 6;
            pub const VT_X2: flatbuffers::VOffsetT = 8;
            pub const VT_Y2: flatbuffers::VOffsetT = 10;
            pub const VT_CONFIDENCE: flatbuffers::VOffsetT = 12;
            pub const VT_CLASS_ID: flatbuffers::VOffsetT = 14;

            #[inline]
            pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
                BoundingBox { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args BoundingBoxArgs,
            ) -> flatbuffers::WIPOffset<BoundingBox<'bldr>> {
                let mut builder = BoundingBoxBuilder::new(_fbb);
                builder.add_class_id(args.class_id);
                builder.add_confidence(args.confidence);
                builder.add_y2(args.y2);
                builder.add_x2(args.x2);
                builder.add_y1(args.y1);
                builder.add_x1(args.x1);
                builder.finish()
            }

            #[inline]
            pub fn x1(&self) -> f32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<f32>(BoundingBox::VT_X1, Some(0.0)).unwrap() }
            }
            #[inline]
            pub fn y1(&self) -> f32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<f32>(BoundingBox::VT_Y1, Some(0.0)).unwrap() }
            }
            #[inline]
            pub fn x2(&self) -> f32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<f32>(BoundingBox::VT_X2, Some(0.0)).unwrap() }
            }
            #[inline]
            pub fn y2(&self) -> f32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<f32>(BoundingBox::VT_Y2, Some(0.0)).unwrap() }
            }
            #[inline]
            pub fn confidence(&self) -> f32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<f32>(BoundingBox::VT_CONFIDENCE, Some(0.0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn class_id(&self) -> u32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u32>(BoundingBox::VT_CLASS_ID, Some(0))
                        .unwrap()
                }
            }
        }

        impl flatbuffers::Verifiable for BoundingBox<'_> {
            #[inline]
            fn run_verifier(
                v: &mut flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
                use self::flatbuffers::Verifiable;
                v.visit_table(pos)?
                    .visit_field::<f32>("x1", Self::VT_X1, false)?
                    .visit_field::<f32>("y1", Self::VT_Y1, false)?
                    .visit_field::<f32>("x2", Self::VT_X2, false)?
                    .visit_field::<f32>("y2", Self::VT_Y2, false)?
                    .visit_field::<f32>("confidence", Self::VT_CONFIDENCE, false)?
                    .visit_field::<u32>("class_id", Self::VT_CLASS_ID, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct BoundingBoxArgs {
            pub x1: f32,
            pub y1: f32,
            pub x2: f32,
            pub y2: f32,
            pub confidence: f32,
            pub class_id: u32,
        }
        impl<'a> Default for BoundingBoxArgs {
            #[inline]
            fn default() -> Self {
                BoundingBoxArgs {
                    x1: 0.0,
                    y1: 0.0,
                    x2: 0.0,
                    y2: 0.0,
                    confidence: 0.0,
                    class_id: 0,
                }
            }
        }

        pub struct BoundingBoxBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
            fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
            start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> BoundingBoxBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_x1(&mut self, x1: f32) {
                self.fbb_.push_slot::<f32>(BoundingBox::VT_X1, x1, 0.0);
            }
            #[inline]
            pub fn add_y1(&mut self, y1: f32) {
                self.fbb_.push_slot::<f32>(BoundingBox::VT_Y1, y1, 0.0);
            }
            #[inline]
            pub fn add_x2(&mut self, x2: f32) {
                self.fbb_.push_slot::<f32>(BoundingBox::VT_X2, x2, 0.0);
            }
            #[inline]
            pub fn add_y2(&mut self, y2: f32) {
                self.fbb_.push_slot::<f32>(BoundingBox::VT_Y2, y2, 0.0);
            }
            #[inline]
            pub fn add_confidence(&mut self, confidence: f32) {
                self.fbb_
                    .push_slot::<f32>(BoundingBox::VT_CONFIDENCE, confidence, 0.0);
            }
            #[inline]
            pub fn add_class_id(&mut self, class_id: u32) {
                self.fbb_
                    .push_slot::<u32>(BoundingBox::VT_CLASS_ID, class_id, 0);
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> BoundingBoxBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                BoundingBoxBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> flatbuffers::WIPOffset<BoundingBox<'a>> {
                let o = self.fbb_.end_table(self.start_);
                flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl core::fmt::Debug for BoundingBox<'_> {
            fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                let mut ds = f.debug_struct("BoundingBox");
                ds.field("x1", &self.x1());
                ds.field("y1", &self.y1());
                ds.field("x2", &self.x2());
                ds.field("y2", &self.y2());
                ds.field("confidence", &self.confidence());
                ds.field("class_id", &self.class_id());
                ds.finish()
            }
        }
        pub enum DetectionResultOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct DetectionResult<'a> {
            pub _tab: flatbuffers::Table<'a>,
        }

        impl<'a> flatbuffers::Follow<'a> for DetectionResult<'a> {
            type Inner = DetectionResult<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: flatbuffers::Table::new(buf, loc),
                }
            }
        }

        impl<'a> DetectionResult<'a> {
            pub const VT_FRAME_NUMBER: flatbuffers::VOffsetT = 4;
            pub const VT_TIMESTAMP_NS: flatbuffers::VOffsetT = 6;
            pub const VT_CAMERA_ID: flatbuffers::VOffsetT = 8;
            pub const VT_DETECTIONS: flatbuffers::VOffsetT = 10;

            #[inline]
            pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
                DetectionResult { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args DetectionResultArgs<'args>,
            ) -> flatbuffers::WIPOffset<DetectionResult<'bldr>> {
                let mut builder = DetectionResultBuilder::new(_fbb);
                builder.add_timestamp_ns(args.timestamp_ns);
                builder.add_frame_number(args.frame_number);
                if let Some(x) = args.detections {
                    builder.add_detections(x);
                }
                builder.add_camera_id(args.camera_id);
                builder.finish()
            }

            #[inline]
            pub fn frame_number(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u64>(DetectionResult::VT_FRAME_NUMBER, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn timestamp_ns(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u64>(DetectionResult::VT_TIMESTAMP_NS, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn camera_id(&self) -> u32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u32>(DetectionResult::VT_CAMERA_ID, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn detections(
                &self,
            ) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<BoundingBox<'a>>>>
            {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<flatbuffers::ForwardsUOffset<
                        flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<BoundingBox>>,
                    >>(DetectionResult::VT_DETECTIONS, None)
                }
            }
        }

        impl flatbuffers::Verifiable for DetectionResult<'_> {
            #[inline]
            fn run_verifier(
                v: &mut flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
                use self::flatbuffers::Verifiable;
                v.visit_table(pos)?
                    .visit_field::<u64>("frame_number", Self::VT_FRAME_NUMBER, false)?
                    .visit_field::<u64>("timestamp_ns", Self::VT_TIMESTAMP_NS, false)?
                    .visit_field::<u32>("camera_id", Self::VT_CAMERA_ID, false)?
                    .visit_field::<flatbuffers::ForwardsUOffset<
                        flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<BoundingBox>>,
                    >>("detections", Self::VT_DETECTIONS, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct DetectionResultArgs<'a> {
            pub frame_number: u64,
            pub timestamp_ns: u64,
            pub camera_id: u32,
            pub detections: Option<
                flatbuffers::WIPOffset<
                    flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<BoundingBox<'a>>>,
                >,
            >,
        }
        impl<'a> Default for DetectionResultArgs<'a> {
            #[inline]
            fn default() -> Self {
                DetectionResultArgs {
                    frame_number: 0,
                    timestamp_ns: 0,
                    camera_id: 0,
                    detections: None,
                }
            }
        }

        pub struct DetectionResultBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
            fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
            start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> DetectionResultBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_frame_number(&mut self, frame_number: u64) {
                self.fbb_
                    .push_slot::<u64>(DetectionResult::VT_FRAME_NUMBER, frame_number, 0);
            }
            #[inline]
            pub fn add_timestamp_ns(&mut self, timestamp_ns: u64) {
                self.fbb_
                    .push_slot::<u64>(DetectionResult::VT_TIMESTAMP_NS, timestamp_ns, 0);
            }
            #[inline]
            pub fn add_camera_id(&mut self, camera_id: u32) {
                self.fbb_
                    .push_slot::<u32>(DetectionResult::VT_CAMERA_ID, camera_id, 0);
            }
            #[inline]
            pub fn add_detections(
                &mut self,
                detections: flatbuffers::WIPOffset<
                    flatbuffers::Vector<'b, flatbuffers::ForwardsUOffset<BoundingBox<'b>>>,
                >,
            ) {
                self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
                    DetectionResult::VT_DETECTIONS,
                    detections,
                );
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> DetectionResultBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                DetectionResultBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> flatbuffers::WIPOffset<DetectionResult<'a>> {
                let o = self.fbb_.end_table(self.start_);
                flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl core::fmt::Debug for DetectionResult<'_> {
            fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                let mut ds = f.debug_struct("DetectionResult");
                ds.field("frame_number", &self.frame_number());
                ds.field("timestamp_ns", &self.timestamp_ns());
                ds.field("camera_id", &self.camera_id());
                ds.field("detections", &self.detections());
                ds.finish()
            }
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a `DetectionResult`
        /// and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_detection_result_unchecked`.
        pub fn root_as_detection_result(
            buf: &[u8],
        ) -> Result<DetectionResult, flatbuffers::InvalidFlatbuffer> {
            flatbuffers::root::<DetectionResult>(buf)
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a size prefixed
        /// `DetectionResult` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `size_prefixed_root_as_detection_result_unchecked`.
        pub fn size_prefixed_root_as_detection_result(
            buf: &[u8],
        ) -> Result<DetectionResult, flatbuffers::InvalidFlatbuffer> {
            flatbuffers::size_prefixed_root::<DetectionResult>(buf)
        }
        #[inline]
        /// Verifies, with the given options, that a buffer of bytes
        /// contains a `DetectionResult` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_detection_result_unchecked`.
        pub fn root_as_detection_result_with_opts<'b, 'o>(
            opts: &'o flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<DetectionResult<'b>, flatbuffers::InvalidFlatbuffer> {
            flatbuffers::root_with_opts::<DetectionResult<'b>>(opts, buf)
        }
        #[inline]
        /// Verifies, with the given verifier options, that a buffer of
        /// bytes contains a size prefixed `DetectionResult` and returns
        /// it. Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_detection_result_unchecked`.
        pub fn size_prefixed_root_as_detection_result_with_opts<'b, 'o>(
            opts: &'o flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<DetectionResult<'b>, flatbuffers::InvalidFlatbuffer> {
            flatbuffers::size_prefixed_root_with_opts::<DetectionResult<'b>>(opts, buf)
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a DetectionResult and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid `DetectionResult`.
        pub unsafe fn root_as_detection_result_unchecked(buf: &[u8]) -> DetectionResult {
            flatbuffers::root_unchecked::<DetectionResult>(buf)
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a size prefixed DetectionResult and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid size prefixed `DetectionResult`.
        pub unsafe fn size_prefixed_root_as_detection_result_unchecked(
            buf: &[u8],
        ) -> DetectionResult {
            flatbuffers::size_prefixed_root_unchecked::<DetectionResult>(buf)
        }
        #[inline]
        pub fn finish_detection_result_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
            fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
            root: flatbuffers::WIPOffset<DetectionResult<'a>>,
        ) {
            fbb.finish(root, None);
        }

        #[inline]
        pub fn finish_size_prefixed_detection_result_buffer<
            'a,
            'b,
            A: flatbuffers::Allocator + 'a,
        >(
            fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
            root: flatbuffers::WIPOffset<DetectionResult<'a>>,
        ) {
            fbb.finish_size_prefixed(root, None);
        }
    } // pub mod schema
} // pub mod bridge
