// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod bridge {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod schema {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_COLOR_FORMAT: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_COLOR_FORMAT: i8 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_COLOR_FORMAT: [ColorFormat; 3] = [
  ColorFormat::BGR,
  ColorFormat::RGB,
  ColorFormat::GRAY,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct ColorFormat(pub i8);
#[allow(non_upper_case_globals)]
impl ColorFormat {
  pub const BGR: Self = Self(0);
  pub const RGB: Self = Self(1);
  pub const GRAY: Self = Self(2);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::BGR,
    Self::RGB,
    Self::GRAY,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::BGR => Some("BGR"),
      Self::RGB => Some("RGB"),
      Self::GRAY => Some("GRAY"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for ColorFormat {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for ColorFormat {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<i8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for ColorFormat {
    type Output = ColorFormat;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<i8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for ColorFormat {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for ColorFormat {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    i8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for ColorFormat {}
pub enum FrameOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Frame<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Frame<'a> {
  type Inner = Frame<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Frame<'a> {
  pub const VT_FRAME_NUMBER: flatbuffers::VOffsetT = 4;
  pub const VT_TIMESTAMP_NS: flatbuffers::VOffsetT = 6;
  pub const VT_CAMERA_ID: flatbuffers::VOffsetT = 8;
  pub const VT_WIDTH: flatbuffers::VOffsetT = 10;
  pub const VT_HEIGHT: flatbuffers::VOffsetT = 12;
  pub const VT_CHANNELS: flatbuffers::VOffsetT = 14;
  pub const VT_FORMAT: flatbuffers::VOffsetT = 16;
  pub const VT_PIXELS: flatbuffers::VOffsetT = 18;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Frame { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args FrameArgs<'args>
  ) -> flatbuffers::WIPOffset<Frame<'bldr>> {
    let mut builder = FrameBuilder::new(_fbb);
    builder.add_timestamp_ns(args.timestamp_ns);
    builder.add_frame_number(args.frame_number);
    if let Some(x) = args.pixels { builder.add_pixels(x); }
    builder.add_height(args.height);
    builder.add_width(args.width);
    builder.add_camera_id(args.camera_id);
    builder.add_format(args.format);
    builder.add_channels(args.channels);
    builder.finish()
  }


  #[inline]
  pub fn frame_number(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Frame::VT_FRAME_NUMBER, Some(0)).unwrap()}
  }
  #[inline]
  pub fn timestamp_ns(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Frame::VT_TIMESTAMP_NS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn camera_id(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Frame::VT_CAMERA_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn width(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Frame::VT_WIDTH, Some(0)).unwrap()}
  }
  #[inline]
  pub fn height(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Frame::VT_HEIGHT, Some(0)).unwrap()}
  }
  #[inline]
  pub fn channels(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(Frame::VT_CHANNELS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn format(&self) -> ColorFormat {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<ColorFormat>(Frame::VT_FORMAT, Some(ColorFormat::BGR)).unwrap()}
  }
  #[inline]
  pub fn pixels(&self) -> Option<flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(Frame::VT_PIXELS, None)}
  }
}

impl flatbuffers::Verifiable for Frame<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("frame_number", Self::VT_FRAME_NUMBER, false)?
     .visit_field::<u64>("timestamp_ns", Self::VT_TIMESTAMP_NS, false)?
     .visit_field::<u32>("camera_id", Self::VT_CAMERA_ID, false)?
     .visit_field::<u32>("width", Self::VT_WIDTH, false)?
     .visit_field::<u32>("height", Self::VT_HEIGHT, false)?
     .visit_field::<u8>("channels", Self::VT_CHANNELS, false)?
     .visit_field::<ColorFormat>("format", Self::VT_FORMAT, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("pixels", Self::VT_PIXELS, false)?
     .finish();
    Ok(())
  }
}
pub struct FrameArgs<'a> {
    pub frame_number: u64,
    pub timestamp_ns: u64,
    pub camera_id: u32,
    pub width: u32,
    pub height: u32,
    pub channels: u8,
    pub format: ColorFormat,
    pub pixels: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for FrameArgs<'a> {
  #[inline]
  fn default() -> Self {
    FrameArgs {
      frame_number: 0,
      timestamp_ns: 0,
      camera_id: 0,
      width: 0,
      height: 0,
      channels: 0,
      format: ColorFormat::BGR,
      pixels: None,
    }
  }
}

pub struct FrameBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> FrameBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_frame_number(&mut self, frame_number: u64) {
    self.fbb_.push_slot::<u64>(Frame::VT_FRAME_NUMBER, frame_number, 0);
  }
  #[inline]
  pub fn add_timestamp_ns(&mut self, timestamp_ns: u64) {
    self.fbb_.push_slot::<u64>(Frame::VT_TIMESTAMP_NS, timestamp_ns, 0);
  }
  #[inline]
  pub fn add_camera_id(&mut self, camera_id: u32) {
    self.fbb_.push_slot::<u32>(Frame::VT_CAMERA_ID, camera_id, 0);
  }
  #[inline]
  pub fn add_width(&mut self, width: u32) {
    self.fbb_.push_slot::<u32>(Frame::VT_WIDTH, width, 0);
  }
  #[inline]
  pub fn add_height(&mut self, height: u32) {
    self.fbb_.push_slot::<u32>(Frame::VT_HEIGHT, height, 0);
  }
  #[inline]
  pub fn add_channels(&mut self, channels: u8) {
    self.fbb_.push_slot::<u8>(Frame::VT_CHANNELS, channels, 0);
  }
  #[inline]
  pub fn add_format(&mut self, format: ColorFormat) {
    self.fbb_.push_slot::<ColorFormat>(Frame::VT_FORMAT, format, ColorFormat::BGR);
  }
  #[inline]
  pub fn add_pixels(&mut self, pixels: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Frame::VT_PIXELS, pixels);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> FrameBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    FrameBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Frame<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Frame<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Frame");
      ds.field("frame_number", &self.frame_number());
      ds.field("timestamp_ns", &self.timestamp_ns());
      ds.field("camera_id", &self.camera_id());
      ds.field("width", &self.width());
      ds.field("height", &self.height());
      ds.field("channels", &self.channels());
      ds.field("format", &self.format());
      ds.field("pixels", &self.pixels());
      ds.finish()
  }
}
}  // pub mod schema
}  // pub mod bridge

